# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    category_menu:
        class: AppBundle\Service\Menu\Category
    customer_menu:
        class: AppBundle\Service\Menu\Customer
    checkout_menu:
        class: AppBundle\Service\Menu\Checkout
    bestsellers:
        class: AppBundle\Service\Menu\BestSellers
    onsale:
        class: AppBundle\Service\Menu\OnSale
    add_to_cart_url:
        class: AppBundle\Service\Menu\AddToCartUrl